# Generated by Django 4.0.6 on 2022-08-26 15:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=15)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, default=False, max_length=20)),
                ('card_name', models.CharField(max_length=12, null=True)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime.now)),
                ('cVV_security_code', models.PositiveSmallIntegerField(default=0)),
                ('card_status', models.CharField(blank=True, default=False, max_length=15)),
                ('signature', models.ImageField(null=True, upload_to='signature')),
                ('issuer', models.CharField(blank=True, default=False, max_length=15)),
                ('account_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, null=True)),
                ('last_name', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('address', models.TextField()),
                ('age', models.PositiveSmallIntegerField()),
                ('nationality', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.PositiveBigIntegerField(default=0)),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=15)),
                ('dulation_months', models.CharField(max_length=10, null=True)),
                ('payment_due_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=20, null=True)),
                ('title', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(max_length=15)),
                ('receipt_date', models.DateTimeField(default=datetime.datetime.now)),
                ('bill_number', models.PositiveBigIntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('file', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=20, null=True)),
                ('account_number', models.PositiveBigIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=20, null=True)),
                ('location', models.CharField(max_length=20, null=True)),
                ('transaction_cost', models.PositiveIntegerField()),
                ('is_Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=12, null=True)),
                ('account_number', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=10, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('third_party', models.CharField(max_length=20, null=True)),
                ('transaction_code', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('user_name', models.CharField(max_length=15, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('pin', models.SmallIntegerField()),
                ('is_active', models.BooleanField()),
                ('type', models.CharField(max_length=15)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reward_transaction', to='wallet.transaction')),
            ],
        ),
    ]
