# Generated by Django 4.0.6 on 2022-08-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_account_card_loan_notification_receipt_reward_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
