# Generated by Django 4.0.6 on 2022-08-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_receipt_receipt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(max_length=15),
        ),
    ]
